### ISSUE TITLE
按照README.md文档，无法正常进行开发

### ISSUE THREAD

**Issue by 15838028035** [backkoms/simplemall#9]
您好！按照README.md文档，无法正常进行开发，是否需要修改什么？
    1、先启动admin-server,eureka-server,conf-server三个基础服务
    2、再依次启动payment/order/product/account基础业务服务
    3、最后启动front-app服务，打开浏览器，输入http://localhost:8088/swagger-ui.html ，根据流程API依次可使用功能[swagger主界面存在bug，不能选择某个api展开收缩，可通过全部展开/收缩的形式使用]
    4、后续有时间再提供页面，基于VUE2+BOOTSTRAP，将流程串起来

**Comment by hehaipeng** [comment]
这个我试过了，是可以正常开发的，你可能哪里配置有问题或者有服务没有安装正确。



pax1122@163.com
 
发件人： 15838028035
发送时间： 2018-03-29 11:19
收件人： backkoms/simplemall
抄送： Subscribed
主题： [backkoms/simplemall] 按照README.md文档，无法正常进行开发 (#9)
您好！按照README.md文档，无法正常进行开发，是否需要修改什么？
1、先启动admin-server,eureka-server,conf-server三个基础服务
2、再依次启动payment/order/product/account基础业务服务
3、最后启动front-app服务，打开浏览器，输入http://localhost:8088/swagger-ui.html ，根据流程API依次可使用功能[swagger主界面存在bug，不能选择某个api展开收缩，可通过全部展开/收缩的形式使用]
4、后续有时间再提供页面，基于VUE2+BOOTSTRAP，将流程串起来

**Comment by 15838028035** [comment]
git@github.com:15838028035/weixindev.git 这个是个demo,你可以帮我看看吗

发自我的 iPhone
